"""Add token_valid_after column for timestamp-based token revocation

Revision ID: 1554f2b83b9f
Revises: 4b2cf18973ab
Create Date: 2025-12-12 12:22:43.417377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1554f2b83b9f'
down_revision = '4b2cf18973ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_valid_after', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_valid_after')

    # ### end Alembic commands ###
